language: node_js
node_js:
  - 14

services:
  - docker

before_script:
  - echo "Travis Run Project 3"
script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed phucla132/udagram-api-feed:latest
  - docker tag udagram-api-user phucla132/udagram-api-user:latest
  - docker tag udagram-frontend phucla132/udagram-frontend:latest
  - docker tag udagram-reverseproxy phucla132/reverseproxy:latest

after_script:
  - docker images

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push phucla132/udagram-api-feed:latest
  - docker push phucla132/udagram-api-user:latest
  - docker push phucla132/udagram-frontend:latest
  - docker push phucla132/reverseproxy:latest